export const styles = {
	// base heading styles
	Heading: `font-pixels text-primaryFg dark:text-primaryFgDark`,
	// sizes
	"Heading--1": `font-[600] text-[2.25rem] md:text-[3rem] lg:text-[4.5rem] leading-[1.1] md:leading-[1.05] lg:leading-[1] -tracking-[0.02em] md:-tracking-[0.03em]`,
	"Heading--2": `font-[600] text-[2rem] md:text-[2.25rem] lg:text-[4rem] leading-[1.2] lg:leading-[1] -tracking-[0.02em] lg:-tracking-[0.03em]`,
	"Heading--3": `font-[600] text-[1.75rem] md:text-[2.25rem] lg:text-[3rem] leading-[1.2] -tracking-[0.02em] lg:-tracking-[0.03em]`,
	// weights
	"Heading--weight-bold": `font-[700] `,
	"Heading-narrow--weight-bold": `font-[700] `,
	"Heading--weight-semibold": `font-[600]`,
	"Heading-narrow--weight-semibold": `font-[600]`,
	"Heading--weight-medium": `font-[500]`,
	"Heading-narrow--weight-medium": `font-[500]`,
	"Heading--weight-regular": `font-[400]`,
	"Heading-narrow--weight-regular": `font-[400]`,
	"Heading-regular--weight-bold": `font-[700] `,
	"Heading-regular--weight-semibold": `font-[600]`,
	"Heading-regular--weight-medium": `font-[500]`,
	"Heading-regular--weight-regular": `font-[400]`,
	"Heading-wide--weight-bold": `font-[700] `,
	"Heading-wide--weight-semibold": `font-[600]`,
	"Heading-wide--weight-medium": `font-[500]`,
	"Heading-wide--weight-regular": `font-[400]`,
	// letter spacing
	"Heading--letter-spacing-condensed": `-tracking-[0.02em] md:-tracking-[0.03em]`,
	"Heading-narrow--letter-spacing-condensed": `-tracking-[0.02em] md:-tracking-[0.03em]`,
	"Heading--letter-spacing-normal": `-tracking-[0.02em] lg:-tracking-[0.03em]`,
	"Heading-narrow--letter-spacing-normal": `-tracking-[0.02em] lg:-tracking-[0.03em]`,
	"Heading--letter-spacing-none": `tracking-0`,
	"Heading-narrow--letter-spacing-none": `tracking-0`,
	"Heading-regular--letter-spacing-condensed": `-tracking-[0.02em] md:-tracking-[0.03em]`,
	"Heading-regular--letter-spacing-normal": `-tracking-[0.02em] lg:-tracking-[0.03em]`,
	"Heading-regular--letter-spacing-none": `tracking-0`,
	"Heading-wide--letter-spacing-condensed": `-tracking-[0.02em] md:-tracking-[0.03em]`,
	"Heading-wide--letter-spacing-normal": `-tracking-[0.02em] lg:-tracking-[0.03em]`,
	"Heading-wide--letter-spacing-none": `tracking-0`,
	// shadow
	"Heading--shadow-extralarge": `Text-shadow--extralarge`,
	"Heading--shadow-large": `Text-shadow--large`,
	"Heading--shadow-medium": `Text-shadow--medium`,
	"Heading--shadow-small": `Text-shadow--small`,
	"Heading--shadow-extrasmall": `Text-shadow--extrasmall`,
	"Heading--shadow-2extrasmall": `Text-shadow--2extrasmall`,
};
